### ISSUE TITLE
provide a SocketFactory for easy integration

### ISSUE THREAD

**Issue by n8fr8** [OperatorFoundation/ShapeshifterAndroidKotlin#1]
The most likely way your library is used on Android is with an HTTP library, such as OkHttp. It would be great to have an out of the box SocketFactory implementation, that could be easily configured and set for an OkHttpClient instance.

An example here:
https://stackoverflow.com/questions/27947506/problems-after-override-socketfactory-with-okhttp

**Comment by consuelita** [comment]
This has been resolved in the [3.3.0](https://github.com/OperatorFoundation/ShapeshifterAndroidKotlin/releases/tag/3.3.0) release.
